[package]
name = "tokio-sunspec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
tokio-modbus = { version = "0.6", default-features = false, features = ["tcp", "server", "tcp-server-unstable"] }
thiserror = "1.0.38"
